use std::sync::Mutex;

use egui::{Context, FontFamily, FontId, RichText, ScrollArea, TextWrapMode};

/// The version for a tagged release, otherwise a description of the commit.
/// Set by `build.rs`.
const VERSION: &str = env!("REMECH2_VERSION");

/// Everything whose license has to ship with the binary, in display order.
const LICENSES: &[(&str, &str)] = &[
    ("ReMech 2", include_str!("../LICENSE.md")),
    ("GeneralUser GS", include_str!("../LICENSE-GUGS.txt")),
    ("Squarish Sans", include_str!("../LICENSE-SquarishSans.txt")),
];

/// Attribution for every crate linked into the binary, generated by
/// `cargo about generate`.
const THIRD_PARTY: &str = include_str!("../THIRD-PARTY.txt");

/// One line of the license box. Headings are drawn brighter but at the same
/// size, so every row stays exactly one line tall.
struct Row {
    text: &'static str,
    heading: bool,
}

/// The license text wrapped to a given number of columns. There is quite a bit
/// of it, which is way too much to lay out as a single label. So it
/// gets split into rows once and drawn a screenful at a time. Re-wrapping only
/// happens when the box changes width.
static ROWS: Mutex<Option<(usize, Vec<Row>)>> = Mutex::new(None);

fn with_rows<R>(columns: usize, draw: impl FnOnce(&[Row]) -> R) -> R {
    let mut cache = ROWS.lock().unwrap();
    if cache.as_ref().is_none_or(|(cached, _)| *cached != columns) {
        *cache = Some((columns, build_rows(columns)));
    }
    let (_, rows) = cache.as_ref().unwrap();
    draw(rows)
}

fn build_rows(columns: usize) -> Vec<Row> {
    let mut rows = Vec::new();
    for (name, text) in LICENSES {
        rows.push(Row {
            text: name,
            heading: true,
        });
        rows.push(Row {
            text: "",
            heading: false,
        });
        wrap_into(text, columns, &mut rows);
        rows.push(Row {
            text: "",
            heading: false,
        });
    }
    wrap_into(THIRD_PARTY, columns, &mut rows);
    rows
}

fn wrap_into(text: &'static str, columns: usize, rows: &mut Vec<Row>) {
    for line in text.lines() {
        if line.starts_with("==") {
            let end = line
                .char_indices()
                .nth(columns)
                .map_or(line.len(), |(index, _)| index);
            rows.push(Row {
                text: &line[..end],
                heading: false,
            });
            continue;
        }

        let mut rest = line;
        loop {
            let Some((limit, _)) = rest.char_indices().nth(columns) else {
                rows.push(Row {
                    text: rest,
                    heading: false,
                });
                break;
            };
            let split = rest[..limit]
                .rfind(' ')
                .filter(|index| *index > 0)
                .unwrap_or(limit);
            rows.push(Row {
                text: rest[..split].trim_end(),
                heading: false,
            });
            rest = rest[split..].trim_start();
        }
    }
}

pub fn window(ctx: &Context, open: &mut bool, scale_factor: f32) {
    egui::Window::new("About")
        .open(open)
        .resizable(false)
        .collapsible(false)
        .pivot(egui::Align2::CENTER_CENTER)
        .default_pos(ctx.content_rect().center())
        .show(ctx, |ui| {
            ui.set_width(240.0 * scale_factor);

            ui.vertical_centered(|ui| {
                ui.label(RichText::new("ReMech 2").size(16.0 * scale_factor).strong());
                ui.label(RichText::new(VERSION).size(8.0 * scale_factor));
                ui.add_space(8.0 * scale_factor);
                ui.label(
                    RichText::new(
                        "ReMech 2 is an unofficial, fan-made project. It is not affiliated with, \
                        endorsed by, or associated with Microsoft, Activision, or any of their \
                        subsidiaries. MechWarrior is a trademark of its respective owner. No original \
                        game content is distributed with this project.",
                    )
                    .size(6.0 * scale_factor),
                );
            });

            ui.add_space(8.0 * scale_factor);

            let font = FontId::new(5.0 * scale_factor, FontFamily::Monospace);
            let (row_height, glyph_width) =
                ui.fonts_mut(|fonts| (fonts.row_height(&font), fonts.glyph_width(&font, ' ')));

            // Leave a couple of columns of slack for the scroll bar.
            let columns = ((ui.available_width() / glyph_width) as usize).saturating_sub(2);

            // Every row is a single line of text, so drop the usual gap.
            ui.spacing_mut().item_spacing.y = 0.0;

            with_rows(columns.max(20), |rows| {
                ScrollArea::vertical()
                    .max_height(1000.0 * scale_factor)
                    .auto_shrink([false, false])
                    .show_rows(ui, row_height, rows.len(), |ui, range| {
                        // The rows are pre-wrapped, so don't let egui wrap them again.
                        ui.style_mut().wrap_mode = Some(TextWrapMode::Extend);
                        for row in &rows[range] {
                            let text = RichText::new(row.text).font(font.clone());
                            ui.label(if row.heading { text.strong() } else { text });
                        }
                    });
            });
        });
}
