use super::*;

/// An list of all bindable actions.
/// Some of these may have not been intended to be exposed to the user.
/// This will almost definitely need refining.
pub static ACTIONS: &[Action] = &[
    axis(
        "throttle",
        "Throttle",
        Movement,
        "throttle",
        Position { relative: true },
        Some(["throttle_plus", "throttle_minus"]),
        6,
        None,
    )
    .rests_off_center(0, -120, 1082)
    .stops_at_rest()
    .set_by("throttle_set")
    .directions("⬆", "⬇"),
    key("reverse_direction", "Reverse Direction", Movement, 63),
    axis(
        "turn_legs",
        "Turn Legs",
        Movement,
        "legs_pan_delta",
        Rate,
        Some(["legs_pan_plus", "legs_pan_minus"]),
        7,
        None,
    )
    .directions("➡", "⬅"),
    key(
        "align_legs_with_torso",
        "Align Legs with Torso",
        Movement,
        17,
    ),
    key("reset_inputs", "Reset Inputs", Movement, 1),
    axis(
        "torso_twist",
        "Torso Twist",
        Torso,
        "torso_pan",
        Position { relative: true },
        Some(["torso_pan_plus", "torso_pan_minus"]),
        3,
        Some("center_torso_twist"),
    )
    .set_by("torso_pan_set")
    .directions("➡", "⬅"),
    hold(
        "center_torso_twist",
        "Center Torso Twist",
        Torso,
        "torso_pan_reset",
    ),
    axis(
        "torso_tilt",
        "Torso Tilt",
        Torso,
        "torso_tilt",
        Position { relative: true },
        Some(["torso_tilt_plus", "torso_tilt_minus"]),
        4,
        Some("center_torso_tilt"),
    )
    .directions("⬆", "⬇"),
    hold(
        "center_torso_tilt",
        "Center Torso Tilt",
        Torso,
        "torso_tilt_reset",
    ),
    hold("jump_jets", "Jump", JumpJets, "jumpjet_enabled"),
    hold(
        "jump_jets_forward",
        "Jump Forward",
        JumpJets,
        "jumpjet_fire_forward",
    )
    .also("jumpjet_enabled"),
    hold(
        "jump_jets_backward",
        "Jump Backward",
        JumpJets,
        "jumpjet_fire_backward",
    )
    .also("jumpjet_enabled"),
    hold(
        "jump_jets_strafe_left",
        "Jump Strafe Left",
        JumpJets,
        "jumpjet_fire_left",
    )
    .also("jumpjet_enabled"),
    hold(
        "jump_jets_strafe_right",
        "Jump Strafe Right",
        JumpJets,
        "jumpjet_fire_right",
    )
    .also("jumpjet_enabled"),
    hold(
        "fire_weapon",
        "Fire Selected Weapon",
        Weapons,
        "weapon_fire",
    ),
    press("next_weapon", "Select Next Weapon", Weapons, "weapon_cycle"),
    hold(
        "fire_group",
        "Fire Selected Group",
        Weapons,
        "weapon_fire_group",
    ),
    hold(
        "fire_group_1",
        "Fire Group 1",
        Weapons,
        "weapon_fire_group_1",
    ),
    hold(
        "fire_group_2",
        "Fire Group 2",
        Weapons,
        "weapon_fire_group_2",
    ),
    hold(
        "fire_group_3",
        "Fire Group 3",
        Weapons,
        "weapon_fire_group_3",
    ),
    press(
        "next_group",
        "Select Next Group",
        Weapons,
        "weapon_cycle_group",
    ),
    press(
        "toggle_group_fire",
        "Toggle Group Fire",
        Weapons,
        "toggle_group_fire",
    ),
    key(
        "add_weapon_to_group_1",
        "Add Weapon to Group 1",
        Weapons,
        151,
    ),
    key(
        "add_weapon_to_group_2",
        "Add Weapon to Group 2",
        Weapons,
        152,
    ),
    key(
        "add_weapon_to_group_3",
        "Add Weapon to Group 3",
        Weapons,
        153,
    ),
    key("jettison_ammo", "Jettison Ammo", Weapons, 20),
    press("next_target", "Next Target", Targeting, "advance_target"),
    press(
        "previous_target",
        "Previous Target",
        Targeting,
        "previous_target",
    ),
    press("reset_target", "Reset Target", Targeting, "reset_target"),
    press(
        "target_reticle",
        "Target at Reticle",
        Targeting,
        "target_reticle",
    ),
    press(
        "target_nearest_enemy",
        "Target Nearest Enemy",
        Targeting,
        "nearest_enemy",
    ),
    press(
        "target_friendly",
        "Target Friendly",
        Targeting,
        "target_friendly",
    ),
    press(
        "target_last_shot",
        "Target Last Shot",
        Targeting,
        "target_last_shot",
    ),
    press(
        "inspect_target",
        "Inspect Target",
        Targeting,
        "inspect_target",
    ),
    key("reset_targeting", "Reset Targeting", Targeting, 39),
    press(
        "next_nav_point",
        "Next Nav Point",
        Navigation,
        "advance_nav",
    ),
    press(
        "previous_nav_point",
        "Previous Nav Point",
        Navigation,
        "previous_nav",
    ),
    press(
        "reset_nav_point",
        "Reset Nav Point",
        Navigation,
        "reset_nav",
    ),
    press("autopilot", "Toggle Autopilot", Navigation, "autopilot"),
    key("punch_in_heading", "Set Autopilot Heading", Navigation, 85),
    key("next_objective", "Next Objective", Navigation, 84),
    key("start_up_mech", "Start Up Mech", MechSystems, 61),
    key("shut_down_mech", "Shut Down Mech", MechSystems, 62),
    key("override_shutdown", "Override Shutdown", MechSystems, 64),
    key("toggle_masc", "Toggle MASC", MechSystems, 86),
    key("infrared", "Infrared Vision", MechSystems, 166),
    key("enhanced_vision", "Enhanced Vision", MechSystems, 167),
    key("eject", "Eject", MechSystems, 59),
    key("toggle_auto_eject", "Toggle Auto-Eject", MechSystems, 60),
    press(
        "self_destruct",
        "Self-Destruct",
        MechSystems,
        "self_destruct",
    ),
    key("cycle_mfd", "Cycle MFD", Displays, 2),
    key("toggle_htal", "Toggle HTAL Display", Displays, 3),
    key("toggle_rear_view", "Toggle Rear View", Displays, 4),
    key("toggle_down_view", "Toggle Down View", Displays, 5),
    key(
        "toggle_weapon_display",
        "Toggle Weapon Display",
        Displays,
        6,
    ),
    key(
        "toggle_damage_display",
        "Toggle Damage Display",
        Displays,
        7,
    ),
    key(
        "toggle_target_display",
        "Toggle Target Display",
        Displays,
        8,
    ),
    key("toggle_hud", "Toggle HUD", Displays, 19),
    key("show_objectives", "Show Objectives", Displays, 65),
    key("next_radar_mode", "Next Radar Mode", Displays, 46),
    key("radar_zoom_in", "Radar Zoom In", Displays, 47),
    key("radar_zoom_out", "Radar Zoom Out", Displays, 48),
    key("radar_reset_zoom", "Radar Reset Zoom", Displays, 49),
    key("toggle_radar_map", "Toggle Radar Map", Displays, 50),
    key("cockpit_view", "Cockpit View", Views, 9),
    key("free_camera_view", "Free Camera View", Views, 10),
    key("tracking_view", "Tracking Camera View", Views, 11),
    key("track_next", "Track Next Object", Views, 12),
    key("track_previous", "Track Previous Object", Views, 13),
    key("ordnance_view", "Weapon Camera View", Views, 14),
    key("cockpit_reset_zoom", "Cockpit Reset Zoom", Views, 23),
    axis(
        "zoom",
        "Zoom",
        Views,
        "zoom_factor",
        Position { relative: false },
        Some(["zoom_factor_plus", "zoom_factor_minus"]),
        6,
        Some("reset_zoom"),
    )
    .rests_off_center(1, 1, 4)
    .directions("⬆", "⬇"),
    hold("reset_zoom", "Reset Zoom", Views, "zoom_factor_reset"),
    axis(
        "look_up_down",
        "Look Up and Down",
        Views,
        "pilot_tilt",
        Position { relative: true },
        Some(["pilot_tilt_plus", "pilot_tilt_minus"]),
        5,
        Some("center_view_tilt"),
    )
    .directions("⬆", "⬇"),
    hold(
        "center_view_tilt",
        "Center View Vertically",
        Views,
        "pilot_tilt_reset",
    ),
    axis(
        "look_left_right",
        "Look Left and Right",
        Views,
        "pilot_pan",
        Position { relative: true },
        Some(["pilot_pan_plus", "pilot_pan_minus"]),
        5,
        Some("center_view_pan"),
    )
    .directions("➡", "⬅"),
    hold(
        "center_view_pan",
        "Center View Horizontally",
        Views,
        "pilot_pan_reset",
    ),
    hold("glance_left", "Glance Left", Views, "glance_left"),
    hold("glance_right", "Glance Right", Views, "glance_right"),
    hold("glance_up", "Glance Up", Views, "glance_up"),
    hold("glance_down", "Glance Down", Views, "glance_down"),
    axis(
        "camera_tilt",
        "Camera Tilt",
        Camera,
        "eyepoint_tilt",
        Position { relative: false },
        Some(["eyepoint_tilt_plus", "eyepoint_tilt_minus"]),
        4,
        Some("reset_camera_tilt"),
    ),
    hold(
        "reset_camera_tilt",
        "Reset Camera Tilt",
        Camera,
        "eyepoint_tilt_reset",
    ),
    axis(
        "camera_pan",
        "Camera Pan",
        Camera,
        "eyepoint_pan_delta",
        Rate,
        Some(["eyepoint_pan_plus", "eyepoint_pan_minus"]),
        4,
        None,
    )
    .directions("➡", "⬅"),
    hold(
        "reset_camera_pan",
        "Reset Camera Pan",
        Camera,
        "eyepoint_pan_reset",
    ),
    axis(
        "camera_slide",
        "Camera Slide",
        Camera,
        "eyepoint_slide_delta",
        Rate,
        Some(["eyepoint_slide_plus", "eyepoint_slide_minus"]),
        6,
        None,
    ),
    axis(
        "camera_distance",
        "Camera Distance",
        Camera,
        "track_distance_delta",
        Rate,
        Some(["track_distance_plus", "track_distance_minus"]),
        6,
        None,
    )
    .directions("⬆", "⬇"),
    axis(
        "camera_height",
        "Camera Height",
        Camera,
        "track_height_delta",
        Rate,
        Some(["track_height_plus", "track_height_minus"]),
        6,
        None,
    )
    .directions("⬆", "⬇"),
    key("user_menu", "User Menu", Lance, 52),
    key("all_points_menu", "All Points Menu", Lance, 53),
    key("point_2_menu", "Point 2 Menu", Lance, 54),
    key("point_3_menu", "Point 3 Menu", Lance, 55),
    key("starmate_menu", "Starmate Menu", Lance, 66),
    key("starmate_1_menu", "Starmate 1 Menu", Lance, 67),
    key("starmate_2_menu", "Starmate 2 Menu", Lance, 68),
    key("starmate_3_menu", "Starmate 3 Menu", Lance, 69),
    key("starmate_4_menu", "Starmate 4 Menu", Lance, 70),
    key("starmate_5_menu", "Starmate 5 Menu", Lance, 71),
    key("starmate_6_menu", "Starmate 6 Menu", Lance, 72),
    key("starmate_7_menu", "Starmate 7 Menu", Lance, 73),
    key("main_menu", "Mission Menu", Game, 51),
    key("pause", "Pause", Game, 88).always(),
    key("help", "Help", Game, 58),
    key("exit_mission", "Exit Mission", Game, 89),
    key("save_screenshot", "Save Screenshot", Game, 91),
    key("about_banner", "About Banner", Game, 90),
    menu_key("menu_up", "Menu: Up", 0xc6),
    menu_key("menu_down", "Menu: Down", 0xc7),
    menu_key("menu_left", "Menu: Left", 0xc9),
    menu_key("menu_right", "Menu: Right", 0xc8),
    press("menu_enter", "Menu: Enter", SimMenu, "menu_enter"),
    press("menu_back", "Menu: Back", SimMenu, "menu_abort"),
    press(
        "next_gamepiece",
        "advance_gamepiece",
        Debug,
        "advance_gamepiece",
    ),
    press(
        "previous_gamepiece",
        "previous_gamepiece",
        Debug,
        "previous_gamepiece",
    ),
    press(
        "reset_gamepiece",
        "reset_gamepiece",
        Debug,
        "reset_gamepiece",
    ),
    press(
        "next_gamething",
        "advance_gamething",
        Debug,
        "advance_gamething",
    ),
    press(
        "previous_gamething",
        "previous_gamething",
        Debug,
        "previous_gamething",
    ),
    press(
        "reset_gamething",
        "reset_gamething",
        Debug,
        "reset_gamething",
    ),
    debug("jump_debugger", "JUMP_DEBUGGER", 15),
    debug("request_ordinance", "REQUEST_ORDINANCE", 16),
    debug("debug_critical_hits_1", "DEBUG_CRITICAL_HITS_1", 92),
    debug("debug_critical_hits_2", "DEBUG_CRITICAL_HITS_2", 93),
    debug("debug_critical_hits_3", "DEBUG_CRITICAL_HITS_3", 94),
    debug("debug_critical_hits_4", "DEBUG_CRITICAL_HITS_4", 95),
    debug("debug_critical_hits_5", "DEBUG_CRITICAL_HITS_5", 96),
    debug("debug_critical_hits_6", "DEBUG_CRITICAL_HITS_6", 97),
    debug("debug_critical_hits_7", "DEBUG_CRITICAL_HITS_7", 98),
    debug("debug_critical_hits_8", "DEBUG_CRITICAL_HITS_8", 99),
    debug("debug_critical_hits_9", "DEBUG_CRITICAL_HITS_9", 100),
    debug("debug_critical_hits_0", "DEBUG_CRITICAL_HITS_0", 101),
    debug("select_head", "SELECT_HEAD", 102),
    debug("select_right_torso", "SELECT_RIGHT_TORSO", 103),
    debug("select_center_torso", "SELECT_CENTER_TORSO", 104),
    debug("select_left_torso", "SELECT_LEFT_TORSO", 105),
    debug("select_right_arm", "SELECT_RIGHT_ARM", 106),
    debug("select_left_arm", "SELECT_LEFT_ARM", 107),
    debug("select_right_leg", "SELECT_RIGHT_LEG", 108),
    debug("select_left_leg", "SELECT_LEFT_LEG", 109),
    debug("ai_0_mono_objectives", "AI_0_MONO_OBJECTIVES", 110),
    debug("ai_1_mono_objectives", "AI_1_MONO_OBJECTIVES", 111),
    debug("ai_2_mono_objectives", "AI_2_MONO_OBJECTIVES", 112),
    debug("ai_3_mono_objectives", "AI_3_MONO_OBJECTIVES", 113),
    debug("ai_4_mono_objectives", "AI_4_MONO_OBJECTIVES", 114),
    debug("ai_5_mono_objectives", "AI_5_MONO_OBJECTIVES", 115),
    debug("ai_6_mono_objectives", "AI_6_MONO_OBJECTIVES", 116),
    debug("ai_7_mono_objectives", "AI_7_MONO_OBJECTIVES", 117),
    debug("ai_8_mono_objectives", "AI_8_MONO_OBJECTIVES", 118),
    debug("ai_9_mono_objectives", "AI_9_MONO_OBJECTIVES", 119),
    debug("objectives_off", "OBJECTIVES_OFF", 120),
    debug("next_mono_objective", "NEXT_MONO_OBJECTIVE", 121),
    debug("prev_mono_objective", "PREV_MONO_OBJECTIVE", 122),
    debug("fail_mono_objective", "FAIL_MONO_OBJECTIVE", 123),
    debug("succeed_mono_objective", "SUCCEED_MONO_OBJECTIVE", 124),
    debug("toggle_gp_text_maps", "TOGGLE_GP_TEXT_MAPS", 125),
    debug("toggle_gt_text_maps", "TOGGLE_GT_TEXT_MAPS", 126),
    debug("toggle_gs_text_maps", "TOGGLE_GS_TEXT_MAPS", 127),
    debug("toggle_terrain_text_maps", "TOGGLE_TERRAIN_TEXT_MAPS", 128),
    debug("go_turbo_control", "GO_TURBO_CONTROL", 129),
    debug("toggle_mem_info", "TOGGLE_MEM_INFO", 130),
    debug("toggle_cache_info", "TOGGLE_CACHE_INFO", 131),
    debug("collision_wireframe", "COLLISION_WIREFRAME", 132),
    debug("toggle_framerate_main", "TOGGLE_FRAMERATE_MAIN", 133),
    debug("toggle_radar_damage", "TOGGLE_RADAR_DAMAGE", 134),
    debug("toggle_scene_info_main", "TOGGLE_SCENE_INFO_MAIN", 135),
    debug("toggle_eye_position_main", "TOGGLE_EYE_POSITION_MAIN", 136),
    debug("toggle_vulnerability", "TOGGLE_VULNERABILITY", 137),
    debug("toggle_ammo_limit", "TOGGLE_AMMO_LIMIT", 138),
    debug("toggle_splash_damage", "TOGGLE_SPLASH_DAMAGE", 139),
    debug("toggle_collision_damage", "TOGGLE_COLLISION_DAMAGE", 140),
    debug("toggle_heat_tracking", "TOGGLE_HEAT_TRACKING", 141),
    debug("toggle_lod_quality", "TOGGLE_LOD_QUALITY", 142),
    debug("dump_cache_once", "DUMP_CACHE_ONCE", 143),
    debug("dump_cache_repeat", "DUMP_CACHE_REPEAT", 144),
    debug("toggle_framerate", "TOGGLE_FRAMERATE", 145),
    debug("crack_mode", "CRACK_MODE", 146),
    debug("toggle_eye_position", "TOGGLE_EYE_POSITION", 147),
    debug("toggle_scene_info", "TOGGLE_SCENE_INFO", 148),
    debug("toggle_wireframe", "TOGGLE_WIREFRAME", 149),
    debug("toggle_palette", "TOGGLE_PALETTE", 150),
    debug("create_navpoint_test", "CREATE_NAVPOINT_TEST", 159),
    debug("delete_navpoint_test", "DELETE_NAVPOINT_TEST", 160),
    debug("toggle_save_frames", "TOGGLE_SAVE_FRAMES", 161),
    debug("play_current_midi", "PLAY_CURRENT_MIDI", 162),
    debug("play_next_midi", "PLAY_NEXT_MIDI", 163),
    debug("hack_jets", "HACK_JETS", 164),
    debug("kill_targetted_mech", "KILL_TARGETTED_MECH", 165),
];
